[package]
name = "ip"
version = "0.1.0"
authors = ["Daniel Sockwell <dsockwell@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.1.20"
bcrypt = "0.6.0"
argonautica = "0.2.0"
base64 = "0.10.1"
