[package]
name = "d5"
version = "0.4.2"
authors = ["Daniel Sockwell <daniel@codesections.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = "0.1.20"
base64 = "0.10.1"



